[workspace]
members = ["orchestrator", "cosmos_gravity", "ethereum_gravity", "gravity_utils", "proto_build", "test_runner", "gravity_proto", "relayer", "gbt"]
default-members = ["gbt"]


[patch.crates-io]
deep_space = { git = "https://github.com/althea-net/deep_space", rev = "b69bc51644f987901613567a8a88d3677e5bcc13" }
