[workspace]
members = ["orchestrator", "cosmos_gravity", "ethereum_gravity", "gravity_utils", "test_runner", "relayer", "gbt", "metrics_exporter"]
default-members = ["gbt"]

[workspace.dependencies]
gravity_proto = "0.2.2"
num256 = "0.5"
clarity = "0.7"
web30 = "0.23"
deep_space = "2.18"
prost = "0.10"
prost-types = "0.10"
tonic = "0.7"
